@echo off
echo 🚀 Iniciando SnorxFit Backend Server...
echo 📁 Navegando al directorio backend...
cd /d "C:\xampp\htdocs\FICTIA\backend"
echo 📍 Directorio actual: %CD%
echo 🌐 Iniciando servidor en puerto 5000...
node server.js
echo ⏸️ Presiona cualquier tecla para cerrar...
pause